exec-once = waybar & hyprpaper

source =  ~/.config/hypr/binds.conf

general{
gaps_in = 5
gaps_out = 8
border_size = 2
resize_on_border = true
allow_tearing = true
layout = dwiddle

col.active_border = rgba(ff3300ee) rgba(ffcc00ee) 45deg
col.inactive_border = rgba(595959aa)

}

input{

	kb_layout = br
	kb_variant = 
	kb_model =
	kb_options =
	kb_rules =

}
